name: Prod Polybot Service Deployment

on:
  push:
    branches:
      - main

env:
  EC2_PUBLIC_IP: 13.60.96.9
  SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
  DOMAIN: prod-bot.abdullahfursa.click:8443

jobs:
  Deploy:
    name: Deploy in EC2
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the app code
      uses: actions/checkout@v2

    - name: SSH to EC2 instance
      run: |
        ssh -o StrictHostKeyChecking=no -i $SSH_PRIVATE_KEY ubuntu@$INSTANCE_IP << 'EOF'
          cd /home/ubuntu/PolybotServicePythonFursa/polybot
          git pull origin main
          source /home/ubuntu/PolybotServicePythonFursa/polybot/venv/bin/activate
          pip install -r requirements.txt
          sudo systemctl restart mybot.service
        EOF
